name=input("Enter your name:")
age=input("enter your age:")
cgpa=input("Enter your cgpa:")
print("student information :")
print("...............")
print("Name:  "+name)
print("Age: ",age)
print("Cgpa; ",cgpa)
